### ISSUE TITLE
Unit Tests For Components/Services Needed

### ISSUE THREAD

**Issue by Dan-Baba** [Dan-Baba/DPS-FrontEnd#18]
- auth service
- event service
- login component
- settings component
- add job component
- edit event component
- event component

**Comment by MParrella823** [comment]
Completed Unit Tests:

- Login Component

- Event Services

- User Services

- App Component

**Comment by MParrella823** [comment]
Stuck on Event Component testing: unsure of what we are actually testing for. Need to discuss with team
