### ISSUE TITLE
Dates Between Server and Frontend Fix

### ISSUE THREAD

**Issue by Dan-Baba** [Dan-Baba/DPS-FrontEnd#27]
### Problem
MySQL DateTime type is too different to the Javascipt Date object. Not an easy solution to convert 1 : 1.

### Solution
Instead of directly translating we will be using Epoch time. When we send a dateTime to the server we need to call `date.getTime()` and pass this. Server will parse it into a dateTime.

When getting data back from the server it will convert it back but we may be off by a few hundred milliseconds, which should be a non issue.

EVERY spot where we send a date, we need to do this. Every spot we get a date, we need to do this.

**Comment by Dan-Baba** [comment]
Correction, only sending TO server do we need to do this. Converting back we can use the string sent by server.

**Comment by MParrella823** [comment]
Can this be marked for review and/or closed?
